### ISSUE TITLE
Unable to set qs on Verify.get()

### ISSUE THREAD

**Issue by ArthurGerbelot** [giftnix/node-telesign#3]
Without access to `qs` options on `Verify.get()` method, we can't call this endpoint to send verify_code to Telesign: 

Document call example: `GET https://rest.telesign.com/v1/verify/AEBC93B5898342F790E4E19FED41A7DA?verify_code=57244 HTTP/1.1` 

If you can just update [this line](https://github.com/giftnix/node-telesign/blob/master/lib/verify.js#L34) 

`qs: null`

with

`qs: options.qs || null`

**Comment by colinhemphill** [comment]
Sorry for the late reply, but I've modified as requested. All API calls that used `qs: null` have been replaced with `qs: options.qs || null` to open up that capability when needed. NPM version 1.1.1 has this feature.
